# Minimal environment containing python, pip to help verify the installation from pypi, without cuda bundled
name: ccc-gpu-test-pypi
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.10
  - pytest
  - libstdcxx-ng
platforms:
  - linux-64
