name: ccc-gpu
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - cmake>=3.15
  - cuda-version>=12.0,<=12.5
  - cupy=13.*
  - minepy
  - pip
  - python=3.10
  - rapids=24.08
  - pip:
    - ipython==8.*
    - numba==0.60.*
    - numpy==1.25.*
    - pandas==1.3.*
    - pre-commit
    - pybind11==2.*
    - pytest==8.*
    - scipy==1.15.*
    - seaborn==0.13.*
    - sphinx==8.*
    - upsetplot==0.9.*
