# Environment for developing, testing, and researching on ccc-gpu
name: ccc-gpu-dev
channels:
  - conda-forge
dependencies:
  - sphinx=8.*
  - mamba
  - conda-lock
platforms:
  - linux-64
    # - win-64
