# Environment for publish ccc-gpu via conda, bundled with CUDA
name: ccc-gpu
channels:
  - conda-forge
  - nvidia
dependencies:
  - mamba
  - conda-lock
  - sphinx
  - pip
  - minepy
  - cmake>=3.15
  - cuda=12.5 # We can refer to Cupy to see how they handle this CUDA dependency, that way we can make ccc-gpu also a pip package
  - cupy=13.*
  - python=3.10
  - ipython=8.*
  - numba=0.60.*
  - numpy=1.26.*
  - pandas=2.2.*
  - pre-commit=4.*
  - pybind11=2.*
  - pytest=8.*
  - scipy=1.15.*
  - scikit-learn=1.6.*
  - seaborn=0.13.*
  - upsetplot=0.9.*
platforms:
  - linux-64
    # - win-64
