# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

# Add the package source dir (libs/) to the path so autodoc can import `ccc`.
sys.path.insert(0, os.path.abspath('../../libs'))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'CCC-GPU'
copyright = '2025-2026, Milton Pividori, Haoyu Zhang, Kevin Fotso, Marc Subirana-Granés'
author = 'Milton Pividori, Haoyu Zhang, Kevin Fotso, Marc Subirana-Granés'

# Single-source the version from the installed package metadata (which comes
# from `[project].version` in pyproject.toml). Falls back to a literal when the
# package is not installed in the docs-build environment (e.g. Read the Docs).
try:
    release = _pkg_version('cccgpu')
except PackageNotFoundError:
    release = '0.2.4'
version = release

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.duration',
    'sphinx.ext.doctest',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',          # For mathematical expressions
    'sphinx.ext.viewcode',         # Add source code links
    'sphinx.ext.githubpages',      # For GitHub Pages compatibility
    'sphinx.ext.napoleon',         # For Google/NumPy style docstrings
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# -- Extension configuration -------------------------------------------------

# intersphinx configuration
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
    'sklearn': ('https://scikit-learn.org/stable/', None),
    'numba': ('https://numba.readthedocs.io/en/stable/', None),
}
intersphinx_disabled_domains = ['std']

# autodoc configuration
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# napoleon configuration for docstring parsing
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages. sphinx_rtd_theme is the theme
# installed by docs/requirements.txt and used on Read the Docs.
html_theme = 'sphinx_rtd_theme'
html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {}

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('index', 'ccc-gpu.tex', 'CCC-GPU Documentation',
     'Milton Pividori, Haoyu Zhang, Kevin Fotso', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'ccc-gpu', 'CCC-GPU Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    ('index', 'ccc-gpu', 'CCC-GPU Documentation',
     author, 'ccc-gpu', 'GPU-accelerated Clustermatch Correlation Coefficient',
     'Miscellaneous'),
]

# -- Options for EPUB output -------------------------------------------------
epub_show_urls = 'footnote'

# -- Read the Docs specific configuration ------------------------------------

# Read the Docs builds in a specific environment, we need to ensure
# compatibility with their build system
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if on_rtd:
    # Mock only the compiled CUDA extension and CUDA-only libraries, which cannot
    # be built/installed on the Read the Docs runners. The pure-Python runtime
    # deps (numpy, numba, scipy, ...) are installed via docs/requirements.txt so
    # autodoc can import and render the real `ccc` docstrings.
    autodoc_mock_imports = ['ccc_cuda_ext', 'cupy', 'rmm']

# MathJax configuration for mathematical expressions
mathjax3_config = {
    'tex': {
        'inlineMath': [['$', '$'], ['\\(', '\\)']],
        'displayMath': [['$$', '$$'], ['\\[', '\\]']],
    }
}
