name: Build Wheels (Simplified)

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to build (e.g., cp311)'
        required: false
        default: 'cp311'
      os:
        description: 'OS to build on'
        required: false
        default: 'ubuntu-24.04'
        type: choice
        options:
          - ubuntu-24.04

jobs:
  build_single_wheel:
    name: Build wheel for ${{ inputs.python_version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment/environment-gpu.yml
          activate-environment: ccc-gpu
          auto-activate-base: false
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Verify CUDA installation
        shell: bash -l {0}
        run: |
          conda info
          nvcc --version

      - name: Install cibuildwheel
        shell: bash -l {0}
        run: python -m pip install cibuildwheel==2.21.3

      - name: Build wheel
        shell: bash -l {0}
        env:
          CIBW_BUILD: "${{ inputs.python_version }}-*"
          CIBW_SKIP: "pp* *-musllinux* *-manylinux_i686 *-manylinux_aarch64 *-win32"
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ inputs.python_version }}-${{ inputs.os }}
          path: ./wheelhouse/*.whl